<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Member;
use App\Models\Cooperative;

class MemberSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get cooperatives
        $picto = Cooperative::where('name', 'Picto Multi-Purpose Cooperative')->first();
        $angeles = Cooperative::where('name', 'Angeles City Credit Cooperative')->first();
        $tarlac = Cooperative::where('name', 'Tarlac Farmers Producers Cooperative')->first();
        $nuevaEcija = Cooperative::where('name', 'Nueva Ecija Marketing Cooperative')->first();
        $bulacan = Cooperative::where('name', 'Bulacan Transport Service Cooperative')->first();
        $batangas = Cooperative::where('name', 'Batangas Multi-Purpose Cooperative')->first();
        $cebu = Cooperative::where('name', 'Cebu Producers Cooperative')->first();
        $davao = Cooperative::where('name', 'Davao Consumers Cooperative')->first();
        $iloilo = Cooperative::where('name', 'Iloilo Service Cooperative')->first();
        $laguna = Cooperative::where('name', 'Laguna Transport Cooperative')->first();
        $mindanao = Cooperative::where('name', 'Mindanao Agrarian Reform Cooperative')->first();
        $northern = Cooperative::where('name', 'Northern Luzon Marketing Cooperative')->first();
        $quezon = Cooperative::where('name', 'Quezon Housing Cooperative')->first();

        // Sample members data
        $members = [
            [
                'coop_id' => $picto?->id,
                'first_name' => 'Maria',
                'last_name' => 'Santos',
                'birth_date' => '1985-03-15',
                'gender' => 'Female',
                'address' => 'Purok 3',
                'region' => 'Region III (Central Luzon)',
                'province' => 'Pampanga',
                'city_municipality' => 'City of San Fernando (Capital)',
                'barangay' => 'San Jose',
                'phone' => '+63 917 123 4567',
                'email' => 'maria.santos@example.com',
                'date_joined' => '2020-01-15',
                'membership_type' => 'Regular',
                'membership_status' => 'Active',
                'share_capital' => 5000.00,
                'educational_attainment' => 'College',
                'primary_livelihood' => 'Rice farming',
                'sector' => 'Farmer',
            ],
            [
                'coop_id' => $picto?->id,
                'first_name' => 'Juan',
                'last_name' => 'Dela Cruz',
                'birth_date' => '1978-07-22',
                'gender' => 'Male',
                'address' => 'Sitio Maligaya',
                'region' => 'Region III (Central Luzon)',
                'province' => 'Pampanga',
                'city_municipality' => 'City of San Fernando (Capital)',
                'barangay' => 'San Jose',
                'phone' => '+63 918 234 5678',
                'email' => 'juan.delacruz@example.com',
                'date_joined' => '2019-05-20',
                'membership_type' => 'Regular',
                'membership_status' => 'Active',
                'share_capital' => 10000.00,
                'educational_attainment' => 'High School',
                'primary_livelihood' => 'Vegetable farming',
                'sector' => 'Farmer',
            ],
            [
                'coop_id' => $angeles?->id,
                'first_name' => 'Rosa',
                'last_name' => 'Garcia',
                'birth_date' => '1990-11-08',
                'gender' => 'Female',
                'address' => '123 Main Street',
                'region' => 'Region III (Central Luzon)',
                'province' => 'Pampanga',
                'city_municipality' => 'City of Angeles',
                'barangay' => 'Balibago',
                'phone' => '+63 919 345 6789',
                'email' => 'rosa.garcia@example.com',
                'date_joined' => '2021-03-10',
                'membership_type' => 'Regular',
                'membership_status' => 'Active',
                'share_capital' => 3000.00,
                'educational_attainment' => 'Vocational',
                'primary_livelihood' => 'Sari-sari store owner',
                'sector' => 'Entrepreneur',
            ],
            [
                'coop_id' => $angeles?->id,
                'first_name' => 'Pedro',
                'last_name' => 'Reyes',
                'birth_date' => '1982-04-18',
                'gender' => 'Male',
                'address' => '456 Rizal Avenue',
                'region' => 'Region III (Central Luzon)',
                'province' => 'Pampanga',
                'city_municipality' => 'City of Angeles',
                'barangay' => 'Balibago',
                'phone' => '+63 920 456 7890',
                'email' => null,
                'date_joined' => '2020-08-05',
                'membership_type' => 'Regular',
                'membership_status' => 'Active',
                'share_capital' => 7500.00,
                'educational_attainment' => 'College',
                'primary_livelihood' => 'Retail business',
                'sector' => 'Entrepreneur',
            ],
            [
                'coop_id' => $tarlac?->id,
                'first_name' => 'Ana',
                'last_name' => 'Mendoza',
                'birth_date' => '1995-09-12',
                'gender' => 'Female',
                'address' => 'Barangay Road',
                'region' => 'Region III (Central Luzon)',
                'province' => 'Tarlac',
                'city_municipality' => 'City of Tarlac (Capital)',
                'barangay' => 'Santa Maria',
                'phone' => '+63 921 567 8901',
                'email' => 'ana.mendoza@example.com',
                'date_joined' => '2022-01-20',
                'membership_type' => 'Regular',
                'membership_status' => 'Active',
                'share_capital' => 2500.00,
                'educational_attainment' => 'High School',
                'primary_livelihood' => 'Corn farming',
                'sector' => 'Farmer',
            ],
            [
                'coop_id' => $tarlac?->id,
                'first_name' => 'Roberto',
                'last_name' => 'Cruz',
                'birth_date' => '1970-12-30',
                'gender' => 'Male',
                'address' => 'Sitio Bagong Silang',
                'region' => 'Region III (Central Luzon)',
                'province' => 'Tarlac',
                'city_municipality' => 'City of Tarlac (Capital)',
                'barangay' => 'Santa Maria',
                'phone' => '+63 922 678 9012',
                'email' => null,
                'date_joined' => '2018-06-15',
                'membership_type' => 'Regular',
                'membership_status' => 'Active',
                'share_capital' => 15000.00,
                'educational_attainment' => 'Elementary',
                'primary_livelihood' => 'Sugarcane farming',
                'sector' => 'Farmer',
            ],
            [
                'coop_id' => $nuevaEcija?->id,
                'first_name' => 'Carmen',
                'last_name' => 'Bautista',
                'birth_date' => '1988-02-25',
                'gender' => 'Female',
                'address' => '789 Highway Road',
                'region' => 'Region III (Central Luzon)',
                'province' => 'Nueva Ecija',
                'city_municipality' => 'City of Cabanatuan (Capital)',
                'barangay' => 'Poblacion',
                'phone' => '+63 923 789 0123',
                'email' => 'carmen.bautista@example.com',
                'date_joined' => '2021-09-12',
                'membership_type' => 'Regular',
                'membership_status' => 'Active',
                'share_capital' => 4000.00,
                'educational_attainment' => 'Vocational',
                'primary_livelihood' => 'Tricycle driver',
                'sector' => 'Employee',
            ],
            [
                'coop_id' => $nuevaEcija?->id,
                'first_name' => 'Miguel',
                'last_name' => 'Fernandez',
                'birth_date' => '1992-06-07',
                'gender' => 'Male',
                'address' => 'Purok 5',
                'region' => 'Region III (Central Luzon)',
                'province' => 'Nueva Ecija',
                'city_municipality' => 'City of Cabanatuan (Capital)',
                'barangay' => 'Poblacion',
                'phone' => '+63 924 890 1234',
                'email' => 'miguel.fernandez@example.com',
                'date_joined' => '2022-04-18',
                'membership_type' => 'Associate',
                'membership_status' => 'Active',
                'share_capital' => 3500.00,
                'educational_attainment' => 'High School',
                'primary_livelihood' => 'Jeepney driver',
                'sector' => 'Employee',
            ],
            [
                'coop_id' => $bulacan?->id,
                'first_name' => 'Liza',
                'last_name' => 'Aquino',
                'birth_date' => '1987-08-19',
                'gender' => 'Female',
                'address' => 'Seaside Road',
                'region' => 'Region III (Central Luzon)',
                'province' => 'Bulacan',
                'city_municipality' => 'Plaridel',
                'barangay' => 'Poblacion',
                'phone' => '+63 925 901 2345',
                'email' => 'liza.aquino@example.com',
                'date_joined' => '2020-11-03',
                'membership_type' => 'Regular',
                'membership_status' => 'Active',
                'share_capital' => 5500.00,
                'educational_attainment' => 'High School',
                'primary_livelihood' => 'Fish vending',
                'sector' => 'Fishfolk',
            ],
            [
                'coop_id' => $bulacan?->id,
                'first_name' => 'Eduardo',
                'last_name' => 'Ramos',
                'birth_date' => '1975-10-14',
                'gender' => 'Male',
                'address' => 'Barangay Coastal',
                'region' => 'Region III (Central Luzon)',
                'province' => 'Bulacan',
                'city_municipality' => 'Plaridel',
                'barangay' => 'Poblacion',
                'phone' => '+63 926 012 3456',
                'email' => null,
                'date_joined' => '2019-02-28',
                'membership_type' => 'Regular',
                'membership_status' => 'Active',
                'share_capital' => 8000.00,
                'educational_attainment' => 'Elementary',
                'primary_livelihood' => 'Fisherman',
                'sector' => 'Fishfolk',
            ],
            [
                'coop_id' => $picto?->id,
                'first_name' => 'Sofia',
                'last_name' => 'Villanueva',
                'birth_date' => '1993-05-03',
                'gender' => 'Female',
                'address' => 'Zone 2',
                'region' => 'Region III (Central Luzon)',
                'province' => 'Pampanga',
                'city_municipality' => 'City of San Fernando (Capital)',
                'barangay' => 'San Jose',
                'phone' => '+63 927 123 4567',
                'email' => 'sofia.villanueva@example.com',
                'date_joined' => '2023-02-10',
                'membership_type' => 'Regular',
                'membership_status' => 'Active',
                'share_capital' => 2000.00,
                'educational_attainment' => 'College',
                'primary_livelihood' => 'Handicraft making',
                'sector' => 'Entrepreneur',
            ],
            // Batangas members
            [
                'coop_id' => $batangas?->id,
                'first_name' => 'Miguel',
                'last_name' => 'Lopez',
                'birth_date' => '1979-02-11',
                'gender' => 'Male',
                'address' => 'Poblacion',
                'region' => 'Region IV-A (CALABARZON)',
                'province' => 'Batangas',
                'city_municipality' => 'Batangas City',
                'barangay' => 'Poblacion',
                'phone' => '+63 930 111 2222',
                'email' => 'miguel.lopez@bmpc.ph',
                'date_joined' => '2005-06-15',
                'membership_type' => 'Regular',
                'membership_status' => 'Active',
                'share_capital' => 5000.00,
                'educational_attainment' => 'High School',
                'primary_livelihood' => 'Fishing',
                'sector' => 'Fishfolk',
            ],
            [
                'coop_id' => $batangas?->id,
                'first_name' => 'Rosalinda',
                'last_name' => 'Navarro',
                'birth_date' => '1986-07-03',
                'gender' => 'Female',
                'address' => 'Barangay San Roque',
                'region' => 'Region IV-A (CALABARZON)',
                'province' => 'Batangas',
                'city_municipality' => 'Batangas City',
                'barangay' => 'San Roque',
                'phone' => '+63 931 222 3333',
                'email' => 'rosalinda.navarro@bmpc.ph',
                'date_joined' => '2010-03-20',
                'membership_type' => 'Regular',
                'membership_status' => 'Active',
                'share_capital' => 3000.00,
                'educational_attainment' => 'College',
                'primary_livelihood' => 'Retail',
                'sector' => 'Entrepreneur',
            ],
            // Cebu members
            [
                'coop_id' => $cebu?->id,
                'first_name' => 'Ramon',
                'last_name' => 'Cruz',
                'birth_date' => '1972-09-13',
                'gender' => 'Male',
                'address' => 'Cebu City',
                'region' => 'Region VII (Central Visayas)',
                'province' => 'Cebu',
                'city_municipality' => 'Cebu City',
                'barangay' => 'Poblacion',
                'phone' => '+63 932 333 4444',
                'email' => 'ramon.cruz@cpc.ph',
                'date_joined' => '1999-11-05',
                'membership_type' => 'Regular',
                'membership_status' => 'Active',
                'share_capital' => 8000.00,
                'educational_attainment' => 'High School',
                'primary_livelihood' => 'Farming',
                'sector' => 'Farmer',
            ],
            [
                'coop_id' => $cebu?->id,
                'first_name' => 'Lourdes',
                'last_name' => 'Reyes',
                'birth_date' => '1988-12-01',
                'gender' => 'Female',
                'address' => 'Barangay Lahug',
                'region' => 'Region VII (Central Visayas)',
                'province' => 'Cebu',
                'city_municipality' => 'Cebu City',
                'barangay' => 'Lahug',
                'phone' => '+63 933 444 5555',
                'email' => 'lourdes.reyes@cpc.ph',
                'date_joined' => '2008-07-22',
                'membership_type' => 'Regular',
                'membership_status' => 'Active',
                'share_capital' => 2500.00,
                'educational_attainment' => 'Vocational',
                'primary_livelihood' => 'Service',
                'sector' => 'Employee',
            ],
            // Davao members
            [
                'coop_id' => $davao?->id,
                'first_name' => 'Jose',
                'last_name' => 'Torres',
                'birth_date' => '1975-04-02',
                'gender' => 'Male',
                'address' => 'Davao City',
                'region' => 'Region XI (Davao Region)',
                'province' => 'Davao del Sur',
                'city_municipality' => 'Davao City',
                'barangay' => 'Poblacion',
                'phone' => '+63 934 555 6666',
                'email' => 'jose.torres@dcc.ph',
                'date_joined' => '2006-01-10',
                'membership_type' => 'Regular',
                'membership_status' => 'Active',
                'share_capital' => 7000.00,
                'educational_attainment' => 'Elementary',
                'primary_livelihood' => 'Retail',
                'sector' => 'Entrepreneur',
            ],
            [
                'coop_id' => $davao?->id,
                'first_name' => 'Marisol',
                'last_name' => 'Hernandez',
                'birth_date' => '1985-05-18',
                'gender' => 'Female',
                'address' => 'Barangay 2',
                'region' => 'Region XI (Davao Region)',
                'province' => 'Davao del Sur',
                'city_municipality' => 'Davao City',
                'barangay' => 'Barangay 2',
                'phone' => '+63 935 666 7777',
                'email' => 'marisol.hernandez@dcc.ph',
                'date_joined' => '2012-09-15',
                'membership_type' => 'Regular',
                'membership_status' => 'Active',
                'share_capital' => 3000.00,
                'educational_attainment' => 'College',
                'primary_livelihood' => 'Teaching',
                'sector' => 'Employee',
            ],
            // Iloilo members
            [
                'coop_id' => $iloilo?->id,
                'first_name' => 'Edgar',
                'last_name' => 'Sanchez',
                'birth_date' => '1980-10-10',
                'gender' => 'Male',
                'address' => 'Iloilo City',
                'region' => 'Region VI (Western Visayas)',
                'province' => 'Iloilo',
                'city_municipality' => 'Iloilo City',
                'barangay' => 'Poblacion',
                'phone' => '+63 936 777 8888',
                'email' => 'edgar.sanchez@isc.ph',
                'date_joined' => '2003-04-22',
                'membership_type' => 'Regular',
                'membership_status' => 'Active',
                'share_capital' => 4500.00,
                'educational_attainment' => 'High School',
                'primary_livelihood' => 'Service',
                'sector' => 'Employee',
            ],
            [
                'coop_id' => $iloilo?->id,
                'first_name' => 'Gloria',
                'last_name' => 'Lopez',
                'birth_date' => '1991-03-05',
                'gender' => 'Female',
                'address' => 'Barangay San Miguel',
                'region' => 'Region VI (Western Visayas)',
                'province' => 'Iloilo',
                'city_municipality' => 'Iloilo City',
                'barangay' => 'San Miguel',
                'phone' => '+63 937 888 9999',
                'email' => 'gloria.lopez@isc.ph',
                'date_joined' => '2015-08-30',
                'membership_type' => 'Regular',
                'membership_status' => 'Active',
                'share_capital' => 2000.00,
                'educational_attainment' => 'College',
                'primary_livelihood' => 'Handicraft',
                'sector' => 'Entrepreneur',
            ],
            // Laguna members
            [
                'coop_id' => $laguna?->id,
                'first_name' => 'Antonio',
                'last_name' => 'Perez',
                'birth_date' => '1976-06-06',
                'gender' => 'Male',
                'address' => 'Sta. Cruz',
                'region' => 'Region IV-A (CALABARZON)',
                'province' => 'Laguna',
                'city_municipality' => 'Sta. Cruz',
                'barangay' => 'Poblacion',
                'phone' => '+63 938 111 2222',
                'email' => 'antonio.perez@ltc.ph',
                'date_joined' => '2011-07-14',
                'membership_type' => 'Regular',
                'membership_status' => 'Active',
                'share_capital' => 4000.00,
                'educational_attainment' => 'High School',
                'primary_livelihood' => 'Transport',
                'sector' => 'Employee',
            ],
            [
                'coop_id' => $laguna?->id,
                'first_name' => 'Rhea',
                'last_name' => 'Santos',
                'birth_date' => '1989-09-09',
                'gender' => 'Female',
                'address' => 'Barangay Central',
                'region' => 'Region IV-A (CALABARZON)',
                'province' => 'Laguna',
                'city_municipality' => 'Sta. Cruz',
                'barangay' => 'Central',
                'phone' => '+63 939 222 3333',
                'email' => 'rhea.santos@ltc.ph',
                'date_joined' => '2013-10-01',
                'membership_type' => 'Regular',
                'membership_status' => 'Active',
                'share_capital' => 2200.00,
                'educational_attainment' => 'Vocational',
                'primary_livelihood' => 'Vendor',
                'sector' => 'Entrepreneur',
            ],
            // Mindanao members
            [
                'coop_id' => $mindanao?->id,
                'first_name' => 'Hector',
                'last_name' => 'Manalo',
                'birth_date' => '1974-01-20',
                'gender' => 'Male',
                'address' => 'General Santos City',
                'region' => 'Region XII (SOCCSKSARGEN)',
                'province' => 'South Cotabato',
                'city_municipality' => 'General Santos City',
                'barangay' => 'Poblacion',
                'phone' => '+63 940 333 4444',
                'email' => 'hector.manalo@marc.ph',
                'date_joined' => '2000-11-11',
                'membership_type' => 'Regular',
                'membership_status' => 'Active',
                'share_capital' => 9000.00,
                'educational_attainment' => 'Elementary',
                'primary_livelihood' => 'Farming',
                'sector' => 'Farmer',
            ],
            [
                'coop_id' => $mindanao?->id,
                'first_name' => 'Estela',
                'last_name' => 'Garcia',
                'birth_date' => '1982-02-02',
                'gender' => 'Female',
                'address' => 'Barangay San Isidro',
                'region' => 'Region XII (SOCCSKSARGEN)',
                'province' => 'South Cotabato',
                'city_municipality' => 'General Santos City',
                'barangay' => 'San Isidro',
                'phone' => '+63 941 444 5555',
                'email' => 'estela.garcia@marc.ph',
                'date_joined' => '2004-03-03',
                'membership_type' => 'Regular',
                'membership_status' => 'Active',
                'share_capital' => 3200.00,
                'educational_attainment' => 'High School',
                'primary_livelihood' => 'Agriculture',
                'sector' => 'Farmer',
            ],
            // Northern Luzon members
            [
                'coop_id' => $northern?->id,
                'first_name' => 'Benjamin',
                'last_name' => 'Torralba',
                'birth_date' => '1968-08-08',
                'gender' => 'Male',
                'address' => 'Laoag City',
                'region' => 'Region I (Ilocos Region)',
                'province' => 'Ilocos Norte',
                'city_municipality' => 'Laoag City',
                'barangay' => 'Poblacion',
                'phone' => '+63 942 555 6666',
                'email' => 'benjamin.torralba@nlmc.ph',
                'date_joined' => '2009-02-17',
                'membership_type' => 'Regular',
                'membership_status' => 'Active',
                'share_capital' => 12000.00,
                'educational_attainment' => 'College',
                'primary_livelihood' => 'Marketing',
                'sector' => 'Entrepreneur',
            ],
            [
                'coop_id' => $northern?->id,
                'first_name' => 'Analyn',
                'last_name' => 'Padilla',
                'birth_date' => '1990-05-05',
                'gender' => 'Female',
                'address' => 'Barangay Rizal',
                'region' => 'Region I (Ilocos Region)',
                'province' => 'Ilocos Norte',
                'city_municipality' => 'Laoag City',
                'barangay' => 'Rizal',
                'phone' => '+63 943 666 7777',
                'email' => 'analyn.padilla@nlmc.ph',
                'date_joined' => '2018-06-20',
                'membership_type' => 'Regular',
                'membership_status' => 'Active',
                'share_capital' => 3500.00,
                'educational_attainment' => 'Vocational',
                'primary_livelihood' => 'Retail',
                'sector' => 'Entrepreneur',
            ],
            // Quezon members
            [
                'coop_id' => $quezon?->id,
                'first_name' => 'Cecilia',
                'last_name' => 'Quintana',
                'birth_date' => '1977-04-04',
                'gender' => 'Female',
                'address' => 'Lucena City',
                'region' => 'Region IV-A (CALABARZON)',
                'province' => 'Quezon',
                'city_municipality' => 'Lucena City',
                'barangay' => 'Poblacion',
                'phone' => '+63 944 777 8888',
                'email' => 'cecilia.quintana@qhc.ph',
                'date_joined' => '2000-08-30',
                'membership_type' => 'Regular',
                'membership_status' => 'Suspended',
                'share_capital' => 2000.00,
                'educational_attainment' => 'High School',
                'primary_livelihood' => 'Housewife',
                'sector' => 'Other',
            ],
            [
                'coop_id' => $quezon?->id,
                'first_name' => 'Rolando',
                'last_name' => 'Guevarra',
                'birth_date' => '1983-12-12',
                'gender' => 'Male',
                'address' => 'Barangay San Roque',
                'region' => 'Region IV-A (CALABARZON)',
                'province' => 'Quezon',
                'city_municipality' => 'Lucena City',
                'barangay' => 'San Roque',
                'phone' => '+63 945 888 9999',
                'email' => 'rolando.guevarra@qhc.ph',
                'date_joined' => '2002-09-10',
                'membership_type' => 'Regular',
                'membership_status' => 'Active',
                'share_capital' => 5000.00,
                'educational_attainment' => 'College',
                'primary_livelihood' => 'Construction',
                'sector' => 'Employee',
            ],
            [
                'coop_id' => $angeles?->id,
                'first_name' => 'Carlos',
                'last_name' => 'Diaz',
                'birth_date' => '1980-01-28',
                'gender' => 'Male',
                'address' => '321 Market Street',
                'region' => 'Region III (Central Luzon)',
                'province' => 'Pampanga',
                'city_municipality' => 'City of Angeles',
                'barangay' => 'Balibago',
                'phone' => '+63 928 234 5678',
                'email' => 'carlos.diaz@example.com',
                'date_joined' => '2017-12-01',
                'membership_type' => 'Regular',
                'membership_status' => 'Suspended',
                'share_capital' => 6000.00,
                'educational_attainment' => 'Vocational',
                'primary_livelihood' => 'Welding services',
                'sector' => 'Employee',
            ],
        ];

        foreach ($members as $member) {
            if (! $member['coop_id']) {
                continue;
            }

            if (! empty($member['email'])) {
                Member::updateOrCreate(
                    ['email' => $member['email']],
                    $member
                );
                continue;
            }

            Member::updateOrCreate(
                [
                    'coop_id' => $member['coop_id'],
                    'first_name' => $member['first_name'],
                    'last_name' => $member['last_name'],
                    'birth_date' => $member['birth_date'],
                ],
                $member
            );
        }
    }
}

