<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Member;
use App\Models\Cooperative;

class MemberSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get cooperatives
        $picto = Cooperative::where('name', 'Picto Multi-Purpose Cooperative')->first();
        $angeles = Cooperative::where('name', 'Angeles City Credit Cooperative')->first();
        $tarlac = Cooperative::where('name', 'Tarlac Farmers Multi-Purpose Cooperative')->first();
        $nuevaEcija = Cooperative::where('name', 'Nueva Ecija Transport Service Cooperative')->first();
        $bulacan = Cooperative::where('name', 'Bulacan Fishermen Cooperative')->first();

        // Sample members data
        $members = [
            [
                'coop_id' => $picto?->id,
                'first_name' => 'Maria',
                'last_name' => 'Santos',
                'birth_date' => '1985-03-15',
                'gender' => 'Female',
                'address' => 'Purok 3',
                'region' => 'Region III (Central Luzon)',
                'province' => 'Pampanga',
                'city_municipality' => 'City of San Fernando (Capital)',
                'barangay' => 'San Jose',
                'phone' => '+63 917 123 4567',
                'email' => 'maria.santos@example.com',
                'date_joined' => '2020-01-15',
                'membership_type' => 'Regular',
                'membership_status' => 'Active',
                'share_capital' => 5000.00,
                'educational_attainment' => 'College',
                'primary_livelihood' => 'Rice farming',
                'sector' => 'Farmer',
            ],
            [
                'coop_id' => $picto?->id,
                'first_name' => 'Juan',
                'last_name' => 'Dela Cruz',
                'birth_date' => '1978-07-22',
                'gender' => 'Male',
                'address' => 'Sitio Maligaya',
                'region' => 'Region III (Central Luzon)',
                'province' => 'Pampanga',
                'city_municipality' => 'City of San Fernando (Capital)',
                'barangay' => 'San Jose',
                'phone' => '+63 918 234 5678',
                'email' => 'juan.delacruz@example.com',
                'date_joined' => '2019-05-20',
                'membership_type' => 'Regular',
                'membership_status' => 'Active',
                'share_capital' => 10000.00,
                'educational_attainment' => 'High School',
                'primary_livelihood' => 'Vegetable farming',
                'sector' => 'Farmer',
            ],
            [
                'coop_id' => $angeles?->id,
                'first_name' => 'Rosa',
                'last_name' => 'Garcia',
                'birth_date' => '1990-11-08',
                'gender' => 'Female',
                'address' => '123 Main Street',
                'region' => 'Region III (Central Luzon)',
                'province' => 'Pampanga',
                'city_municipality' => 'City of Angeles',
                'barangay' => 'Balibago',
                'phone' => '+63 919 345 6789',
                'email' => 'rosa.garcia@example.com',
                'date_joined' => '2021-03-10',
                'membership_type' => 'Regular',
                'membership_status' => 'Active',
                'share_capital' => 3000.00,
                'educational_attainment' => 'Vocational',
                'primary_livelihood' => 'Sari-sari store owner',
                'sector' => 'Entrepreneur',
            ],
            [
                'coop_id' => $angeles?->id,
                'first_name' => 'Pedro',
                'last_name' => 'Reyes',
                'birth_date' => '1982-04-18',
                'gender' => 'Male',
                'address' => '456 Rizal Avenue',
                'region' => 'Region III (Central Luzon)',
                'province' => 'Pampanga',
                'city_municipality' => 'City of Angeles',
                'barangay' => 'Balibago',
                'phone' => '+63 920 456 7890',
                'email' => null,
                'date_joined' => '2020-08-05',
                'membership_type' => 'Regular',
                'membership_status' => 'Active',
                'share_capital' => 7500.00,
                'educational_attainment' => 'College',
                'primary_livelihood' => 'Retail business',
                'sector' => 'Entrepreneur',
            ],
            [
                'coop_id' => $tarlac?->id,
                'first_name' => 'Ana',
                'last_name' => 'Mendoza',
                'birth_date' => '1995-09-12',
                'gender' => 'Female',
                'address' => 'Barangay Road',
                'region' => 'Region III (Central Luzon)',
                'province' => 'Tarlac',
                'city_municipality' => 'City of Tarlac (Capital)',
                'barangay' => 'Santa Maria',
                'phone' => '+63 921 567 8901',
                'email' => 'ana.mendoza@example.com',
                'date_joined' => '2022-01-20',
                'membership_type' => 'Regular',
                'membership_status' => 'Active',
                'share_capital' => 2500.00,
                'educational_attainment' => 'High School',
                'primary_livelihood' => 'Corn farming',
                'sector' => 'Farmer',
            ],
            [
                'coop_id' => $tarlac?->id,
                'first_name' => 'Roberto',
                'last_name' => 'Cruz',
                'birth_date' => '1970-12-30',
                'gender' => 'Male',
                'address' => 'Sitio Bagong Silang',
                'region' => 'Region III (Central Luzon)',
                'province' => 'Tarlac',
                'city_municipality' => 'City of Tarlac (Capital)',
                'barangay' => 'Santa Maria',
                'phone' => '+63 922 678 9012',
                'email' => null,
                'date_joined' => '2018-06-15',
                'membership_type' => 'Regular',
                'membership_status' => 'Active',
                'share_capital' => 15000.00,
                'educational_attainment' => 'Elementary',
                'primary_livelihood' => 'Sugarcane farming',
                'sector' => 'Farmer',
            ],
            [
                'coop_id' => $nuevaEcija?->id,
                'first_name' => 'Carmen',
                'last_name' => 'Bautista',
                'birth_date' => '1988-02-25',
                'gender' => 'Female',
                'address' => '789 Highway Road',
                'region' => 'Region III (Central Luzon)',
                'province' => 'Nueva Ecija',
                'city_municipality' => 'City of Cabanatuan (Capital)',
                'barangay' => 'Poblacion',
                'phone' => '+63 923 789 0123',
                'email' => 'carmen.bautista@example.com',
                'date_joined' => '2021-09-12',
                'membership_type' => 'Regular',
                'membership_status' => 'Active',
                'share_capital' => 4000.00,
                'educational_attainment' => 'Vocational',
                'primary_livelihood' => 'Tricycle driver',
                'sector' => 'Employee',
            ],
            [
                'coop_id' => $nuevaEcija?->id,
                'first_name' => 'Miguel',
                'last_name' => 'Fernandez',
                'birth_date' => '1992-06-07',
                'gender' => 'Male',
                'address' => 'Purok 5',
                'region' => 'Region III (Central Luzon)',
                'province' => 'Nueva Ecija',
                'city_municipality' => 'City of Cabanatuan (Capital)',
                'barangay' => 'Poblacion',
                'phone' => '+63 924 890 1234',
                'email' => 'miguel.fernandez@example.com',
                'date_joined' => '2022-04-18',
                'membership_type' => 'Associate',
                'membership_status' => 'Active',
                'share_capital' => 3500.00,
                'educational_attainment' => 'High School',
                'primary_livelihood' => 'Jeepney driver',
                'sector' => 'Employee',
            ],
            [
                'coop_id' => $bulacan?->id,
                'first_name' => 'Liza',
                'last_name' => 'Aquino',
                'birth_date' => '1987-08-19',
                'gender' => 'Female',
                'address' => 'Seaside Road',
                'region' => 'Region III (Central Luzon)',
                'province' => 'Bulacan',
                'city_municipality' => 'Plaridel',
                'barangay' => 'Poblacion',
                'phone' => '+63 925 901 2345',
                'email' => 'liza.aquino@example.com',
                'date_joined' => '2020-11-03',
                'membership_type' => 'Regular',
                'membership_status' => 'Active',
                'share_capital' => 5500.00,
                'educational_attainment' => 'High School',
                'primary_livelihood' => 'Fish vending',
                'sector' => 'Fishfolk',
            ],
            [
                'coop_id' => $bulacan?->id,
                'first_name' => 'Eduardo',
                'last_name' => 'Ramos',
                'birth_date' => '1975-10-14',
                'gender' => 'Male',
                'address' => 'Barangay Coastal',
                'region' => 'Region III (Central Luzon)',
                'province' => 'Bulacan',
                'city_municipality' => 'Plaridel',
                'barangay' => 'Poblacion',
                'phone' => '+63 926 012 3456',
                'email' => null,
                'date_joined' => '2019-02-28',
                'membership_type' => 'Regular',
                'membership_status' => 'Active',
                'share_capital' => 8000.00,
                'educational_attainment' => 'Elementary',
                'primary_livelihood' => 'Fisherman',
                'sector' => 'Fishfolk',
            ],
            [
                'coop_id' => $picto?->id,
                'first_name' => 'Sofia',
                'last_name' => 'Villanueva',
                'birth_date' => '1993-05-03',
                'gender' => 'Female',
                'address' => 'Zone 2',
                'region' => 'Region III (Central Luzon)',
                'province' => 'Pampanga',
                'city_municipality' => 'City of San Fernando (Capital)',
                'barangay' => 'San Jose',
                'phone' => '+63 927 123 4567',
                'email' => 'sofia.villanueva@example.com',
                'date_joined' => '2023-02-10',
                'membership_type' => 'Regular',
                'membership_status' => 'Active',
                'share_capital' => 2000.00,
                'educational_attainment' => 'College',
                'primary_livelihood' => 'Handicraft making',
                'sector' => 'Entrepreneur',
            ],
            [
                'coop_id' => $angeles?->id,
                'first_name' => 'Carlos',
                'last_name' => 'Diaz',
                'birth_date' => '1980-01-28',
                'gender' => 'Male',
                'address' => '321 Market Street',
                'region' => 'Region III (Central Luzon)',
                'province' => 'Pampanga',
                'city_municipality' => 'City of Angeles',
                'barangay' => 'Balibago',
                'phone' => '+63 928 234 5678',
                'email' => 'carlos.diaz@example.com',
                'date_joined' => '2017-12-01',
                'membership_type' => 'Regular',
                'membership_status' => 'Suspended',
                'share_capital' => 6000.00,
                'educational_attainment' => 'Vocational',
                'primary_livelihood' => 'Welding services',
                'sector' => 'Employee',
            ],
        ];

        foreach ($members as $member) {
            if ($member['coop_id']) {
                Member::create($member);
            }
        }
    }
}

